import '../models/swipe_item.dart';

class SeedDataService {
  // Dimensions Ref:
  // 0: Tech/Gadgets, 1: Nature/Outdoors, 2: Fashion/Style, 3: Luxury/Premium, 4: Budget/Practical,
  // 5: Cozy/Home, 6: Active/Wellness, 7: Creative/Geek, 8: Art/Design, 9: Food/Drink

  // Canonical, model-aligned tags for the 10 dimensions above.
  static const List<String> _dimensionTags = [
    'Tech',
    'Outdoors',
    'Style',
    'Luxury',
    'Budget',
    'Cozy',
    'Active',
    'Geek',
    'Art',
    'Food',
  ];

  static List<SwipeItem> getAllItems() {
    final items = <SwipeItem>[
      // --- AESTHETICS & VIBES (25 ITEMS) ---
      SwipeItem(
        id: 'aes_dark_academia',
        name: 'Dark Academia',
        description: 'Leather books, gold ink, and tweed.',
        imageUrl: 'unsplash:Dark Academia',
        tags: ['Aesthetic', 'Vintage'],
        vector: [0.1, 0.0, 0.8, 0.4, 0.0, 0.9, 0.0, 0.7, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'aes_vaporwave',
        name: 'Vaporwave',
        description: '90s nostalgia and neon glitch.',
        imageUrl: 'unsplash:Vaporwave',
        tags: ['Aesthetic', 'Retro'],
        vector: [0.7, 0.0, 0.5, 0.2, 0.0, 0.0, 0.0, 1.0, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'aes_scandi',
        name: 'Scandinavian Minimalist',
        description: 'Bright, clean, and functional.',
        imageUrl: 'unsplash:Scandinavian Minimalist',
        tags: ['Aesthetic', 'Modern'],
        vector: [0.2, 0.3, 0.6, 0.5, 0.4, 0.9, 0.0, 0.1, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'aes_streetwear',
        name: 'Hypebeast / Streetwear',
        description: 'Bold logos and urban culture.',
        imageUrl: 'unsplash:Hypebeast / Streetwear',
        tags: ['Aesthetic', 'Fashion'],
        vector: [0.2, 0.0, 1.0, 0.7, 0.0, 0.0, 0.6, 0.3, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'aes_boho',
        name: 'Bohemian / Boho',
        description: 'Free-spirited, earthy, and patterned.',
        imageUrl: 'unsplash:Bohemian / Boho',
        tags: ['Aesthetic', 'Nature'],
        vector: [0.0, 0.8, 0.7, 0.1, 0.4, 0.9, 0.0, 0.2, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'aes_gorpcore',
        name: 'Gorpcore',
        description: 'Technical outdoor gear as high fashion.',
        imageUrl: 'unsplash:Gorpcore',
        tags: ['Aesthetic', 'Outdoors'],
        vector: [0.6, 1.0, 0.9, 0.5, 0.0, 0.1, 0.8, 0.2, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'aes_midcentury',
        name: 'Mid-Century Modern',
        description: '1950s sleek lines and wood tones.',
        imageUrl: 'unsplash:Mid-Century Modern',
        tags: ['Aesthetic', 'Classic'],
        vector: [0.1, 0.0, 0.5, 0.8, 0.0, 0.6, 0.0, 0.4, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'aes_cyberpunk',
        name: 'Cyberpunk',
        description: 'High tech, low life, neon rain.',
        imageUrl: 'unsplash:Cyberpunk',
        tags: ['Aesthetic', 'Tech'],
        vector: [1.0, 0.0, 0.4, 0.3, 0.0, 0.0, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'aes_old_money',
        name: 'Old Money / Preppy',
        description: 'Quiet luxury and timeless staples.',
        imageUrl: 'unsplash:Old Money / Preppy',
        tags: ['Aesthetic', 'Luxury'],
        vector: [0.0, 0.2, 0.9, 1.0, 0.0, 0.4, 0.3, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'aes_grunge',
        name: '90s Grunge',
        description: 'Flannels and raw edges.',
        imageUrl: 'unsplash:90s Grunge',
        tags: ['Aesthetic', 'Retro'],
        vector: [0.0, 0.0, 0.9, 0.0, 0.7, 0.5, 0.0, 0.8, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'aes_cottagecore',
        name: 'Cottagecore',
        description: 'Rural life and soft nature.',
        imageUrl: 'unsplash:Cottagecore',
        tags: ['Aesthetic', 'Cozy'],
        vector: [0.0, 1.0, 0.4, 0.0, 0.5, 1.0, 0.1, 0.0, 0.6, 0.2],
      ),
      SwipeItem(
        id: 'aes_industrial',
        name: 'Industrial Urban',
        description: 'Exposed metal and brick.',
        imageUrl: 'unsplash:Industrial Urban',
        tags: ['Aesthetic', 'City'],
        vector: [0.4, 0.0, 0.4, 0.3, 0.2, 0.2, 0.0, 0.3, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'aes_japandi',
        name: 'Japandi',
        description: 'Japanese function meets Scandi warmth.',
        imageUrl: 'unsplash:Japandi',
        tags: ['Aesthetic', 'Calm'],
        vector: [0.1, 0.5, 0.5, 0.3, 0.2, 0.9, 0.0, 0.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'aes_grandmillennial',
        name: 'Grandmillennial',
        description: 'Chintz, needlepoint, and "granny chic."',
        imageUrl: 'unsplash:Grandmillennial',
        tags: ['Aesthetic', 'Retro'],
        vector: [0.0, 0.2, 0.6, 0.4, 0.3, 0.9, 0.0, 0.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'aes_techwear',
        name: 'Techwear',
        description: 'Ninja-like tactical functionality.',
        imageUrl: 'unsplash:Techwear',
        tags: ['Aesthetic', 'Cyber'],
        vector: [0.9, 0.2, 0.9, 0.6, 0.0, 0.0, 0.5, 0.4, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'aes_art_deco',
        name: 'Art Deco',
        description: 'Geometric luxury and gold accents.',
        imageUrl: 'unsplash:Art Deco',
        tags: ['Aesthetic', 'Gold'],
        vector: [0.1, 0.0, 0.5, 1.0, 0.0, 0.4, 0.0, 0.2, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'aes_y2k',
        name: 'Y2K / Futuristic',
        description: 'Shiny fabrics and early 2000s tech.',
        imageUrl: 'unsplash:Y2K / Futuristic',
        tags: ['Aesthetic', 'Silver'],
        vector: [0.7, 0.0, 1.0, 0.4, 0.2, 0.0, 0.0, 0.8, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'aes_minimalism',
        name: 'Hard Minimalism',
        description: 'Monochrome and empty spaces.',
        imageUrl: 'unsplash:Hard Minimalism',
        tags: ['Aesthetic', 'Clean'],
        vector: [0.3, 0.0, 0.7, 0.7, 0.4, 0.6, 0.0, 0.1, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'aes_maximalism',
        name: 'Colorful Maximalism',
        description: 'More is more. Bold colors and patterns.',
        imageUrl: 'unsplash:Colorful Maximalism',
        tags: ['Aesthetic', 'Bold'],
        vector: [0.1, 0.2, 0.9, 0.4, 0.0, 0.5, 0.0, 0.3, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'aes_coastal',
        name: 'Coastal Grandmother',
        description: 'Linen, white wine, and ocean breezes.',
        imageUrl: 'unsplash:Coastal Grandmother',
        tags: ['Aesthetic', 'Soft'],
        vector: [0.0, 0.6, 0.8, 0.7, 0.1, 1.0, 0.1, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'aes_soft_boy',
        name: 'Soft Boy / Girl',
        description: 'Pastels, oversized knits, and art kits.',
        imageUrl: 'unsplash:Soft Boy / Girl',
        tags: ['Aesthetic', 'Kind'],
        vector: [0.0, 0.3, 0.8, 0.1, 0.4, 1.0, 0.0, 0.2, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'aes_dark_mori',
        name: 'Dark Mori',
        description: 'Forest witch vibes and layered rags.',
        imageUrl: 'unsplash:Dark Mori',
        tags: ['Aesthetic', 'Forest'],
        vector: [0.0, 0.9, 0.7, 0.2, 0.3, 0.8, 0.0, 0.6, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'aes_light_academia',
        name: 'Light Academia',
        description: 'Beige linen, museums, and poetry.',
        imageUrl: 'unsplash:Light Academia',
        tags: ['Aesthetic', 'Art'],
        vector: [0.0, 0.2, 0.7, 0.5, 0.2, 0.9, 0.0, 0.4, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'aes_steampunk',
        name: 'Steampunk',
        description: 'Victorian era meets brass gears.',
        imageUrl: 'unsplash:Steampunk',
        tags: ['Aesthetic', 'Gears'],
        vector: [0.5, 0.0, 0.6, 0.4, 0.2, 0.2, 0.0, 1.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'aes_skate',
        name: 'Surf / Skate Culture',
        description: 'Sun-bleached tees and loose fits.',
        imageUrl: 'unsplash:Surf / Skate Culture',
        tags: ['Aesthetic', 'Summer'],
        vector: [0.0, 0.4, 1.0, 0.1, 0.6, 0.3, 0.8, 0.2, 0.5, 0.0],
      ),

      // --- COLORS (25 ITEMS) ---
      SwipeItem(
        id: 'col_forest_green',
        name: 'Forest Green',
        description: 'Deep, earthy tones.',
        imageUrl: 'unsplash:Forest Green',
        tags: ['Color'],
        vector: [0.0, 1.0, 0.4, 0.2, 0.0, 0.6, 0.0, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'col_navy',
        name: 'Navy Blue',
        description: 'Professional and stable.',
        imageUrl: 'unsplash:Navy Blue',
        tags: ['Color'],
        vector: [0.1, 0.0, 0.5, 0.6, 0.2, 0.4, 0.0, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'col_terracotta',
        name: 'Terracotta',
        description: 'Warm baked clay.',
        imageUrl: 'unsplash:Terracotta',
        tags: ['Color'],
        vector: [0.0, 0.6, 0.4, 0.1, 0.2, 0.8, 0.0, 0.1, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'col_matte_black',
        name: 'Matte Black',
        description: 'Sleek and stealthy.',
        imageUrl: 'unsplash:Matte Black',
        tags: ['Color'],
        vector: [0.8, 0.0, 0.6, 0.7, 0.1, 0.2, 0.0, 0.4, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'col_lavender',
        name: 'Lavender',
        description: 'Soft and floral.',
        imageUrl: 'unsplash:Lavender',
        tags: ['Color'],
        vector: [0.0, 0.4, 0.5, 0.1, 0.3, 1.0, 0.0, 0.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'col_burgundy',
        name: 'Burgundy',
        description: 'Rich and sophisticated.',
        imageUrl: 'unsplash:Burgundy',
        tags: ['Color'],
        vector: [0.0, 0.0, 0.7, 0.9, 0.0, 0.4, 0.0, 0.1, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'col_mustard',
        name: 'Mustard Yellow',
        description: 'Retro and bold.',
        imageUrl: 'unsplash:Mustard Yellow',
        tags: ['Color'],
        vector: [0.0, 0.2, 0.6, 0.0, 0.5, 0.5, 0.0, 0.6, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'col_sage',
        name: 'Sage Green',
        description: 'Muted botanical calm.',
        imageUrl: 'unsplash:Sage Green',
        tags: ['Color'],
        vector: [0.0, 0.8, 0.3, 0.1, 0.4, 0.9, 0.0, 0.1, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'col_electric_blue',
        name: 'Electric Blue',
        description: 'High-energy digital.',
        imageUrl: 'unsplash:Electric Blue',
        tags: ['Color'],
        vector: [0.7, 0.0, 0.5, 0.3, 0.2, 0.0, 0.5, 0.9, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'col_rose_gold',
        name: 'Rose Gold',
        description: 'Soft metallic luxury.',
        imageUrl: 'unsplash:Rose Gold',
        tags: ['Color'],
        vector: [0.3, 0.0, 0.6, 0.8, 0.1, 0.7, 0.0, 0.2, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'col_mauve',
        name: 'Mauve',
        description: 'Dusty, muted purple.',
        imageUrl: 'unsplash:Mauve',
        tags: ['Color'],
        vector: [0.0, 0.3, 0.6, 0.3, 0.3, 0.9, 0.0, 0.1, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'col_ochre',
        name: 'Ochre',
        description: 'Golden, earthy yellow.',
        imageUrl: 'unsplash:Ochre',
        tags: ['Color'],
        vector: [0.0, 0.6, 0.5, 0.2, 0.4, 0.7, 0.0, 0.3, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'col_charcoal',
        name: 'Charcoal Grey',
        description: 'Heavy and grounded.',
        imageUrl: 'unsplash:Charcoal Grey',
        tags: ['Color'],
        vector: [0.3, 0.1, 0.5, 0.4, 0.5, 0.6, 0.0, 0.2, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'col_teal',
        name: 'Teal',
        description: 'Deep ocean blue-green.',
        imageUrl: 'unsplash:Teal',
        tags: ['Color'],
        vector: [0.1, 0.7, 0.5, 0.4, 0.2, 0.6, 0.2, 0.1, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'col_cream',
        name: 'Cream / Beige',
        description: 'Clean and neutral.',
        imageUrl: 'unsplash:Cream / Beige',
        tags: ['Color'],
        vector: [0.0, 0.2, 0.7, 0.4, 0.4, 1.0, 0.0, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'col_emerald',
        name: 'Emerald Green',
        description: 'Vibrant jewel tone.',
        imageUrl: 'unsplash:Emerald Green',
        tags: ['Color'],
        vector: [0.0, 0.6, 0.5, 1.0, 0.0, 0.3, 0.0, 0.2, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'col_plum',
        name: 'Plum',
        description: 'Deep, mysterious purple.',
        imageUrl: 'unsplash:Plum',
        tags: ['Color'],
        vector: [0.0, 0.2, 0.6, 0.8, 0.0, 0.5, 0.0, 0.3, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'col_slate',
        name: 'Slate Blue',
        description: 'Cool and industrial.',
        imageUrl: 'unsplash:Slate Blue',
        tags: ['Color'],
        vector: [0.2, 0.3, 0.6, 0.3, 0.4, 0.6, 0.0, 0.3, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'col_copper',
        name: 'Copper',
        description: 'Brilliant metallic orange.',
        imageUrl: 'unsplash:Copper',
        tags: ['Color'],
        vector: [0.2, 0.1, 0.4, 0.7, 0.1, 0.5, 0.0, 0.4, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'col_olive',
        name: 'Olive Drab',
        description: 'Classic utilitarian green.',
        imageUrl: 'unsplash:Olive Drab',
        tags: ['Color'],
        vector: [0.1, 0.9, 0.7, 0.2, 0.6, 0.3, 0.5, 0.2, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'col_peach',
        name: 'Peach',
        description: 'Soft, summer-fruit tone.',
        imageUrl: 'unsplash:Peach',
        tags: ['Color'],
        vector: [0.0, 0.4, 0.6, 0.2, 0.4, 0.9, 0.0, 0.1, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'col_mint',
        name: 'Mint Green',
        description: 'Fresh and energetic.',
        imageUrl: 'unsplash:Mint Green',
        tags: ['Color'],
        vector: [0.0, 0.5, 0.5, 0.1, 0.6, 0.8, 0.3, 0.2, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'col_cobalt',
        name: 'Cobalt Blue',
        description: 'Deep and brilliant.',
        imageUrl: 'unsplash:Cobalt Blue',
        tags: ['Color'],
        vector: [0.1, 0.1, 0.7, 0.4, 0.2, 0.2, 0.0, 0.4, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'col_camel',
        name: 'Camel Tan',
        description: 'Warm and high-end.',
        imageUrl: 'unsplash:Camel Tan',
        tags: ['Color'],
        vector: [0.0, 0.1, 0.9, 0.8, 0.2, 0.7, 0.0, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'col_gunmetal',
        name: 'Gunmetal',
        description: 'Dark, technical metallic.',
        imageUrl: 'unsplash:Gunmetal',
        tags: ['Color'],
        vector: [0.6, 0.0, 0.5, 0.5, 0.2, 0.2, 0.0, 0.6, 0.4, 0.0],
      ),

      // --- CLOTHING TYPES (40 ITEMS) ---
      SwipeItem(
        id: 'clot_overcoat',
        name: 'Wool Overcoat',
        description: 'Tailored warmth.',
        imageUrl: 'unsplash:Wool Overcoat',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.9, 0.8, 0.0, 0.3, 0.0, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_hoodie',
        name: 'Oversized Hoodie',
        description: 'Pure comfort staple.',
        imageUrl: 'unsplash:Oversized Hoodie',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.5, 0.0, 0.8, 1.0, 0.2, 0.1, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'clot_chelsea',
        name: 'Chelsea Boots',
        description: 'Sleek leather.',
        imageUrl: 'unsplash:Chelsea Boots',
        tags: ['Shoes'],
        vector: [0.0, 0.2, 0.9, 0.7, 0.0, 0.3, 0.2, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_puffer',
        name: 'Puffer Jacket',
        description: 'Insulated winter layer.',
        imageUrl: 'unsplash:Puffer Jacket',
        tags: ['Clothing'],
        vector: [0.2, 0.8, 0.7, 0.3, 0.2, 0.5, 0.7, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'clot_linen',
        name: 'Linen Shirt',
        description: 'Summer breathable fabric.',
        imageUrl: 'unsplash:Linen Shirt',
        tags: ['Clothing'],
        vector: [0.0, 0.5, 0.8, 0.4, 0.1, 0.6, 0.3, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_denim',
        name: 'Selvedge Denim',
        description: 'Raw indigo jeans.',
        imageUrl: 'unsplash:Selvedge Denim',
        tags: ['Clothing'],
        vector: [0.0, 0.2, 1.0, 0.5, 0.4, 0.2, 0.2, 0.7, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_turtleneck',
        name: 'Turtleneck',
        description: 'Sleek knitwear layer.',
        imageUrl: 'unsplash:Turtleneck',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.8, 0.6, 0.2, 0.9, 0.0, 0.2, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'clot_trench',
        name: 'Trench Coat',
        description: 'Iconic rain protection.',
        imageUrl: 'unsplash:Trench Coat',
        tags: ['Clothing'],
        vector: [0.0, 0.4, 0.9, 0.7, 0.1, 0.4, 0.2, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_beanie',
        name: 'Cashmere Beanie',
        description: 'Soft premium warmth.',
        imageUrl: 'unsplash:Cashmere Beanie',
        tags: ['Accessory'],
        vector: [0.0, 0.3, 0.6, 0.8, 0.2, 1.0, 0.0, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_loafers',
        name: 'Penny Loafers',
        description: 'Slip-on preppy shoes.',
        imageUrl: 'unsplash:Penny Loafers',
        tags: ['Shoes'],
        vector: [0.0, 0.0, 0.9, 0.8, 0.1, 0.3, 0.0, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_bomber',
        name: 'MA-1 Bomber',
        description: 'Streetwear staple.',
        imageUrl: 'unsplash:MA-1 Bomber',
        tags: ['Clothing'],
        vector: [0.1, 0.0, 0.9, 0.3, 0.4, 0.2, 0.3, 0.6, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_cardigan',
        name: 'Chunky Cardigan',
        description: 'Cozy layered knit.',
        imageUrl: 'unsplash:Chunky Cardigan',
        tags: ['Clothing'],
        vector: [0.0, 0.1, 0.5, 0.2, 0.4, 1.0, 0.0, 0.1, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_cargo',
        name: 'Tactical Cargoes',
        description: 'Multi-pocket utility.',
        imageUrl: 'unsplash:Tactical Cargoes',
        tags: ['Clothing'],
        vector: [0.4, 0.4, 0.9, 0.2, 0.5, 0.2, 0.4, 0.6, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'clot_silk_scarf',
        name: 'Silk Scarf',
        description: 'Patterned luxury.',
        imageUrl: 'unsplash:Silk Scarf',
        tags: ['Accessory'],
        vector: [0.0, 0.0, 0.7, 0.9, 0.1, 0.5, 0.0, 0.2, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'clot_windbreaker',
        name: '90s Windbreaker',
        description: 'Neon outdoor layer.',
        imageUrl: 'unsplash:90s Windbreaker',
        tags: ['Clothing'],
        vector: [0.3, 0.6, 0.7, 0.1, 0.5, 0.1, 0.8, 0.7, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_maxi',
        name: 'Floral Maxi Dress',
        description: 'Boho flowing silhouette.',
        imageUrl: 'unsplash:Floral Maxi Dress',
        tags: ['Clothing'],
        vector: [0.0, 0.7, 0.8, 0.3, 0.4, 0.8, 0.2, 0.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_shearling',
        name: 'Shearling Jacket',
        description: 'Rugged wool-lined warmth.',
        imageUrl: 'unsplash:Shearling Jacket',
        tags: ['Clothing'],
        vector: [0.0, 0.5, 0.9, 0.8, 0.0, 0.7, 0.3, 0.2, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_parka',
        name: 'Technical Parka',
        description: 'Heavy weather protection.',
        imageUrl: 'unsplash:Technical Parka',
        tags: ['Clothing'],
        vector: [0.3, 0.9, 0.8, 0.6, 0.1, 0.4, 0.7, 0.2, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_chinos',
        name: 'Slim Chinos',
        description: 'Daily versatile trousers.',
        imageUrl: 'unsplash:Slim Chinos',
        tags: ['Clothing'],
        vector: [0.0, 0.1, 0.8, 0.4, 0.6, 0.5, 0.2, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_oxford',
        name: 'Oxford Button-Down',
        description: 'Formal or casual staple.',
        imageUrl: 'unsplash:Oxford Button-Down',
        tags: ['Clothing'],
        vector: [0.0, 0.1, 0.8, 0.6, 0.4, 0.5, 0.2, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_flannel',
        name: 'Heavy Flannel',
        description: 'Plaid rugged warmth.',
        imageUrl: 'unsplash:Heavy Flannel',
        tags: ['Clothing'],
        vector: [0.0, 0.8, 0.9, 0.1, 0.6, 0.7, 0.4, 0.3, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_slip',
        name: 'Silk Slip Dress',
        description: 'Elegant evening wear.',
        imageUrl: 'unsplash:Silk Slip Dress',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.9, 0.8, 0.0, 0.4, 0.0, 0.1, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'clot_blazer',
        name: 'Unstructured Blazer',
        description: 'Relaxed formal jacket.',
        imageUrl: 'unsplash:Unstructured Blazer',
        tags: ['Clothing'],
        vector: [0.0, 0.1, 0.9, 0.7, 0.3, 0.4, 0.2, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_combat',
        name: 'Combat Boots',
        description: 'Rugged platform tread.',
        imageUrl: 'unsplash:Combat Boots',
        tags: ['Shoes'],
        vector: [0.0, 0.4, 1.0, 0.4, 0.4, 0.3, 0.5, 0.7, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_tote',
        name: 'Canvas Tote',
        description: 'Heavy-duty daily carrier.',
        imageUrl: 'unsplash:Canvas Tote',
        tags: ['Bag'],
        vector: [0.0, 0.3, 0.6, 0.1, 0.9, 0.7, 0.3, 0.4, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_crossbody',
        name: 'Leather Crossbody',
        description: 'Sleek minimalist bag.',
        imageUrl: 'unsplash:Leather Crossbody',
        tags: ['Bag'],
        vector: [0.0, 0.1, 0.9, 0.8, 0.3, 0.4, 0.2, 0.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'clot_messenger',
        name: 'Tech Messenger Bag',
        description: 'Utilitarian urban carry.',
        imageUrl: 'unsplash:Tech Messenger Bag',
        tags: ['Bag'],
        vector: [0.7, 0.2, 0.9, 0.5, 0.3, 0.2, 0.5, 0.6, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_belt',
        name: 'Vegetable Tanned Belt',
        description: 'High-quality leather.',
        imageUrl: 'unsplash:Vegetable Tanned Belt',
        tags: ['Accessory'],
        vector: [0.0, 0.3, 0.8, 0.6, 0.5, 0.2, 0.1, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'clot_shades',
        name: 'Acetate Sunglasses',
        description: 'Timeless face shape.',
        imageUrl: 'unsplash:Acetate Sunglasses',
        tags: ['Accessory'],
        vector: [0.0, 0.2, 0.9, 0.8, 0.1, 0.2, 0.4, 0.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'clot_watch',
        name: 'Field Watch',
        description: 'Rugged analog time.',
        imageUrl: 'unsplash:Field Watch',
        tags: ['Accessory'],
        vector: [0.4, 0.8, 0.6, 0.5, 0.4, 0.2, 0.6, 0.3, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_sneaker',
        name: 'Minimalist Sneaker',
        description: 'White leather daily shoe.',
        imageUrl: 'unsplash:Minimalist Sneaker',
        tags: ['Shoes'],
        vector: [0.0, 0.1, 0.9, 0.6, 0.6, 0.5, 0.3, 0.2, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'clot_sandal',
        name: 'Strappy Sandal',
        description: 'Summer leather light.',
        imageUrl: 'unsplash:Strappy Sandal',
        tags: ['Shoes'],
        vector: [0.0, 0.4, 0.8, 0.3, 0.4, 0.6, 0.4, 0.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_heel',
        name: 'Pointed Toe Heel',
        description: 'Sharp evening footwear.',
        imageUrl: 'unsplash:Pointed Toe Heel',
        tags: ['Shoes'],
        vector: [0.0, 0.0, 0.9, 0.9, 0.0, 0.0, 0.0, 0.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'clot_mules',
        name: 'Leather Mules',
        description: 'Easy slip-on elegance.',
        imageUrl: 'unsplash:Leather Mules',
        tags: ['Shoes'],
        vector: [0.0, 0.1, 0.9, 0.7, 0.2, 0.6, 0.0, 0.1, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'clot_clogs',
        name: 'Garden Clogs',
        description: 'Rubber functional footwear.',
        imageUrl: 'unsplash:Garden Clogs',
        tags: ['Shoes'],
        vector: [0.0, 0.9, 0.2, 0.0, 0.9, 0.7, 0.4, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'clot_swim',
        name: 'Tailored Swim Shorts',
        description: 'Quick dry luxury.',
        imageUrl: 'unsplash:Tailored Swim Shorts',
        tags: ['Clothing'],
        vector: [0.0, 0.6, 0.7, 0.6, 0.2, 0.0, 0.9, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'clot_loungewear',
        name: 'Loungewear',
        description: 'Soft, comfortable indoor wear.',
        imageUrl: 'unsplash:Loungewear Cozy',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.6, 0.2, 0.6, 1.0, 0.2, 0.1, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'clot_pjs',
        name: 'Silk Pajamas',
        description: 'Luxury sleeping attire.',
        imageUrl: 'unsplash:Silk Pajamas',
        tags: ['Clothing'],
        vector: [0.0, 0.0, 0.6, 0.9, 0.1, 1.0, 0.0, 0.1, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'clot_active',
        name: 'Seamless Leggings',
        description: 'High compression gym wear.',
        imageUrl: 'unsplash:Seamless Leggings',
        tags: ['Clothing'],
        vector: [0.1, 0.2, 0.7, 0.4, 0.3, 0.5, 1.0, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'clot_shorts',
        name: 'Technical Running Shorts',
        description: 'Ultralight performance.',
        imageUrl: 'unsplash:Technical Running Shorts',
        tags: ['Clothing'],
        vector: [0.2, 0.5, 0.5, 0.3, 0.4, 0.1, 1.0, 0.1, 0.0, 0.0],
      ),

      // --- BRANDS (STYLE & LIFESTYLE - 35 ITEMS) ---
      SwipeItem(
        id: 'cbr_carhartt',
        name: 'Carhartt WIP',
        description: 'Rugged street workwear.',
        imageUrl: 'unsplash:Carhartt WIP',
        tags: ['Brand'],
        vector: [0.0, 0.6, 0.8, 0.2, 0.6, 0.4, 0.5, 0.2, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_stone',
        name: 'Stone Island',
        description: 'High-end tech style.',
        imageUrl: 'unsplash:Stone Island',
        tags: ['Brand'],
        vector: [0.5, 0.2, 1.0, 0.9, 0.0, 0.0, 0.6, 0.4, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_everlane',
        name: 'Everlane',
        description: 'Ethical basics.',
        imageUrl: 'unsplash:Everlane',
        tags: ['Brand'],
        vector: [0.0, 0.3, 0.9, 0.4, 0.5, 0.7, 0.1, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cbr_acne',
        name: 'Acne Studios',
        description: 'Swedish fashion house.',
        imageUrl: 'unsplash:Acne Studios',
        tags: ['Brand'],
        vector: [0.0, 0.0, 1.0, 0.9, 0.0, 0.3, 0.0, 0.4, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'cbr_ralph',
        name: 'Ralph Lauren',
        description: 'American preppy.',
        imageUrl: 'unsplash:Ralph Lauren',
        tags: ['Brand'],
        vector: [0.0, 0.2, 0.8, 0.9, 0.2, 0.4, 0.3, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_patagonia',
        name: 'Patagonia',
        description: 'Eco-conscious outdoors.',
        imageUrl: 'unsplash:Patagonia',
        tags: ['Brand'],
        vector: [0.1, 1.0, 0.6, 0.4, 0.2, 0.4, 0.9, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'cbr_arcteryx',
        name: 'Arc\'teryx',
        description: 'Elite technical alpine.',
        imageUrl: 'unsplash:Arc\'teryx Jacket Outdoor Climbing',
        tags: ['Brand'],
        vector: [0.5, 1.0, 0.8, 0.8, 0.0, 0.2, 0.9, 0.2, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_stussy',
        name: 'Stüssy',
        description: 'Original surf/skate street.',
        imageUrl: 'unsplash:Stüssy',
        tags: ['Brand'],
        vector: [0.1, 0.1, 1.0, 0.3, 0.4, 0.2, 0.5, 0.7, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cbr_barbour',
        name: 'Barbour',
        description: 'Waxed cotton heritage.',
        imageUrl: 'unsplash:Barbour',
        tags: ['Brand'],
        vector: [0.0, 0.7, 0.7, 0.8, 0.1, 0.5, 0.4, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_uniqlo',
        name: 'Uniqlo',
        description: 'High-value Japanese basics.',
        imageUrl: 'unsplash:Uniqlo',
        tags: ['Brand'],
        vector: [0.1, 0.1, 0.7, 0.1, 1.0, 0.6, 0.2, 0.1, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_madewell',
        name: 'Madewell',
        description: 'Effortless denim.',
        imageUrl: 'unsplash:Madewell',
        tags: ['Brand'],
        vector: [0.0, 0.2, 0.9, 0.4, 0.5, 0.7, 0.1, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_offwhite',
        name: 'Off-White',
        description: 'Bold graphic luxury.',
        imageUrl: 'unsplash:Off-White',
        tags: ['Brand'],
        vector: [0.4, 0.0, 1.0, 1.0, 0.0, 0.0, 0.2, 0.6, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'cbr_drmartens',
        name: 'Dr. Martens',
        description: 'Yellow-stitch boots.',
        imageUrl: 'unsplash:Dr. Martens',
        tags: ['Brand'],
        vector: [0.0, 0.2, 0.9, 0.3, 0.4, 0.4, 0.6, 0.6, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cbr_birken',
        name: 'Birkenstock',
        description: 'Cork-bed comfort.',
        imageUrl: 'unsplash:Birkenstock',
        tags: ['Brand'],
        vector: [0.0, 0.7, 0.6, 0.2, 0.5, 0.8, 0.3, 0.1, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_vans',
        name: 'Vans',
        description: 'Skate heritage.',
        imageUrl: 'unsplash:Vans',
        tags: ['Brand'],
        vector: [0.0, 0.2, 0.9, 0.1, 0.8, 0.3, 0.7, 0.4, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_converse',
        name: 'Converse',
        description: 'Chuck Taylor All Stars.',
        imageUrl: 'unsplash:Converse',
        tags: ['Brand'],
        vector: [0.0, 0.1, 0.8, 0.1, 0.9, 0.4, 0.3, 0.5, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_nike',
        name: 'Nike',
        description: 'Athletic dominance.',
        imageUrl: 'unsplash:Nike',
        tags: ['Brand'],
        vector: [0.2, 0.2, 0.8, 0.5, 0.3, 0.1, 1.0, 0.3, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cbr_adidas',
        name: 'Adidas',
        description: 'Three-stripe lifestyle.',
        imageUrl: 'unsplash:Adidas',
        tags: ['Brand'],
        vector: [0.1, 0.1, 0.8, 0.4, 0.4, 0.2, 0.9, 0.4, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cbr_lulu',
        name: 'Lululemon',
        description: 'Yoga performance.',
        imageUrl: 'unsplash:Lululemon',
        tags: ['Brand'],
        vector: [0.1, 0.2, 0.7, 0.7, 0.2, 0.6, 1.0, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_alo',
        name: 'Alo Yoga',
        description: 'Studio to street style.',
        imageUrl: 'unsplash:Alo Yoga',
        tags: ['Brand'],
        vector: [0.1, 0.1, 0.8, 0.8, 0.1, 0.5, 1.0, 0.2, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_ov',
        name: 'Outdoor Voices',
        description: 'Recreational athletic.',
        imageUrl: 'unsplash:Outdoor Voices',
        tags: ['Brand'],
        vector: [0.0, 0.4, 0.7, 0.3, 0.5, 0.5, 1.0, 0.3, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cbr_theory',
        name: 'Theory',
        description: 'Modern office minimalism.',
        imageUrl: 'unsplash:Theory',
        tags: ['Brand'],
        vector: [0.0, 0.0, 0.9, 0.8, 0.2, 0.4, 0.1, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_apc',
        name: 'A.P.C.',
        description: 'Parisian cool basics.',
        imageUrl: 'unsplash:A.P.C.',
        tags: ['Brand'],
        vector: [0.0, 0.1, 1.0, 0.8, 0.3, 0.5, 0.0, 0.2, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cbr_ganni',
        name: 'Ganni',
        description: 'Playful Scandi fashion.',
        imageUrl: 'unsplash:Ganni',
        tags: ['Brand'],
        vector: [0.0, 0.1, 0.9, 0.8, 0.1, 0.4, 0.1, 0.3, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'cbr_sezane',
        name: 'Sézane',
        description: 'French romantic chic.',
        imageUrl: 'unsplash:Sézane',
        tags: ['Brand'],
        vector: [0.0, 0.3, 0.9, 0.7, 0.2, 0.8, 0.0, 0.2, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'cbr_ref',
        name: 'Reformation',
        description: 'Sustainable feminine style.',
        imageUrl: 'unsplash:Reformation',
        tags: ['Brand'],
        vector: [0.0, 0.5, 0.9, 0.8, 0.1, 0.7, 0.0, 0.1, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cbr_allbirds',
        name: 'Allbirds',
        description: 'Sustainable wool shoes.',
        imageUrl: 'unsplash:Allbirds',
        tags: ['Brand'],
        vector: [0.0, 0.6, 0.6, 0.4, 0.6, 0.8, 0.5, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_on',
        name: 'On Running',
        description: 'Cloud-tech footwear.',
        imageUrl: 'unsplash:On Running',
        tags: ['Brand'],
        vector: [0.3, 0.3, 0.7, 0.6, 0.4, 0.2, 1.0, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_hoka',
        name: 'Hoka',
        description: 'Max cushion runners.',
        imageUrl: 'unsplash:Hoka',
        tags: ['Brand'],
        vector: [0.1, 0.6, 0.7, 0.4, 0.5, 0.2, 1.0, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cbr_brooks',
        name: 'Brooks',
        description: 'Pure running heritage.',
        imageUrl: 'unsplash:Brooks',
        tags: ['Brand'],
        vector: [0.0, 0.5, 0.5, 0.2, 0.7, 0.1, 1.0, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'cbr_salomon',
        name: 'Salomon',
        description: 'Trail-ready fashion.',
        imageUrl: 'unsplash:Salomon',
        tags: ['Brand'],
        vector: [0.4, 1.0, 0.8, 0.6, 0.2, 0.1, 1.0, 0.4, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_newbalance',
        name: 'New Balance',
        description: 'Classic comfort icons.',
        imageUrl: 'unsplash:New Balance',
        tags: ['Brand'],
        vector: [0.1, 0.2, 0.9, 0.5, 0.7, 0.6, 0.6, 0.4, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cbr_reebok',
        name: 'Reebok',
        description: 'Retro athletic style.',
        imageUrl: 'unsplash:Reebok',
        tags: ['Brand'],
        vector: [0.0, 0.1, 0.8, 0.2, 0.7, 0.4, 0.8, 0.5, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'cbr_puma',
        name: 'Puma',
        description: 'Sporty sleek design.',
        imageUrl: 'unsplash:Puma',
        tags: ['Brand'],
        vector: [0.1, 0.1, 0.8, 0.3, 0.6, 0.3, 0.9, 0.4, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cbr_champion',
        name: 'Champion',
        description: 'Reverse weave hoodies.',
        imageUrl: 'unsplash:Champion',
        tags: ['Brand'],
        vector: [0.0, 0.0, 0.6, 0.1, 0.8, 0.9, 0.4, 0.2, 0.1, 0.0],
      ),

      // --- TECH GADGETS (35 ITEMS) ---
      SwipeItem(
        id: 'tgad_kb',
        name: 'Mechanical Keyboard',
        description: 'Tactile typing.',
        imageUrl: 'unsplash:Mechanical Keyboard',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.3, 0.4, 0.2, 0.5, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'brand_fujifilm',
        name: 'Fujifilm',
        description: 'Photography brand.',
        imageUrl: 'unsplash:Fujifilm',
        tags: ['Brand', 'Tech', 'Art'],
        vector: [0.4, 0.2, 0.4, 0.3, 0.5, 0.4, 0.2, 0.3, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'cat_instant_photography',
        name: 'Instant Photography',
        description: 'Physical prints and snapshots.',
        imageUrl: 'unsplash:Instant Photography',
        tags: ['Category', 'Tech', 'Art'],
        vector: [0.4, 0.3, 0.5, 0.2, 0.5, 0.6, 0.3, 0.3, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'tgad_headphones',
        name: 'ANC Headphones',
        description: 'Silence the noise.',
        imageUrl: 'unsplash:ANC Headphones',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.4, 0.7, 0.2, 0.4, 0.2, 0.6, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'tgad_kindle',
        name: 'E-Reader',
        description: 'Library in a tablet.',
        imageUrl: 'unsplash:E-Reader',
        tags: ['Tech'],
        vector: [0.8, 0.0, 0.1, 0.4, 0.6, 0.9, 0.0, 0.8, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'brand_magsafe',
        name: 'MagSafe',
        description: 'Snap-on ecosystem.',
        imageUrl: 'unsplash:MagSafe',
        tags: ['Brand', 'Tech'],
        vector: [0.9, 0.0, 0.1, 0.4, 0.5, 0.1, 0.2, 0.3, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cat_portable_charging',
        name: 'Portable Charging',
        description: 'Power banks and on-the-go battery.',
        imageUrl: 'unsplash:Portable Charger Power Bank',
        tags: ['Category', 'Tech', 'Budget'],
        vector: [0.9, 0.0, 0.1, 0.3, 0.7, 0.1, 0.3, 0.2, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_lamp',
        name: 'Smart RGB Lamp',
        description: 'Mood lighting.',
        imageUrl: 'unsplash:Smart RGB Lamp',
        tags: ['Tech'],
        vector: [0.9, 0.0, 0.1, 0.3, 0.6, 0.7, 0.0, 0.9, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'tgad_projector',
        name: 'Mini Projector',
        description: 'Movies anywhere.',
        imageUrl: 'unsplash:Mini Projector',
        tags: ['Tech'],
        vector: [0.9, 0.1, 0.1, 0.5, 0.4, 0.8, 0.1, 0.6, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'brand_dji',
        name: 'DJI',
        description: 'Drone brand.',
        imageUrl: 'unsplash:DJI Drone',
        tags: ['Brand', 'Tech'],
        vector: [1.0, 0.4, 0.1, 0.6, 0.2, 0.0, 0.5, 0.3, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cat_drones_aerial',
        name: 'Drones & Aerial Photos',
        description: 'Flying cameras and aerial footage.',
        imageUrl: 'unsplash:Aerial Drone Photography',
        tags: ['Category', 'Tech', 'Art', 'Outdoors'],
        vector: [1.0, 0.5, 0.1, 0.5, 0.2, 0.0, 0.5, 0.3, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'tgad_massage',
        name: 'Massage Gun',
        description: 'Muscle recovery.',
        imageUrl: 'unsplash:Massage Gun',
        tags: ['Tech'],
        vector: [0.8, 0.1, 0.1, 0.7, 0.2, 0.4, 1.0, 0.2, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_keychron',
        name: 'Wireless Mec KB',
        description: 'Modern mechanical.',
        imageUrl: 'unsplash:Wireless Mac KB',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.2, 0.4, 0.5, 0.4, 0.0, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'tgad_airtag',
        name: 'Item Tracker',
        description: 'Never lose keys.',
        imageUrl: 'unsplash:Item Tracker',
        tags: ['Tech'],
        vector: [0.9, 0.2, 0.1, 0.3, 0.7, 0.0, 0.2, 0.2, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_speaker',
        name: 'BT Speaker',
        description: 'Waterproof sound.',
        imageUrl: 'unsplash:BT Speaker',
        tags: ['Tech'],
        vector: [0.7, 0.9, 0.2, 0.3, 0.4, 0.2, 0.8, 0.3, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'tgad_plug',
        name: 'Smart Plug',
        description: 'App control home.',
        imageUrl: 'unsplash:Smart Plug',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.2, 0.8, 0.4, 0.0, 0.5, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_ring',
        name: 'LED Ring Light',
        description: 'Perfect lighting.',
        imageUrl: 'unsplash:LED Ring Light',
        tags: ['Tech'],
        vector: [0.8, 0.0, 0.2, 0.3, 0.5, 0.1, 0.0, 0.9, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'tgad_webcam',
        name: '4K Webcam',
        description: 'Crystal clear calls.',
        imageUrl: 'unsplash:4K Webcam',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.4, 0.4, 0.1, 0.0, 0.8, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'tgad_ssd',
        name: 'External SSD',
        description: 'Fast file storage.',
        imageUrl: 'unsplash:External SSD',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.4, 0.5, 0.0, 0.0, 0.6, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'tgad_mouse',
        name: 'Vertical Mouse',
        description: 'Ergonomic precision.',
        imageUrl: 'unsplash:Vertical Mouse',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.2, 0.4, 0.2, 0.0, 0.9, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'tgad_mousepad',
        name: 'Leather Desk Mat',
        description: 'Sleek workspace.',
        imageUrl: 'unsplash:Leather Desk Mat',
        tags: ['Office'],
        vector: [0.2, 0.1, 0.8, 0.7, 0.4, 0.4, 0.0, 0.6, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'tgad_monitor_light',
        name: 'Monitor Light Bar',
        description: 'No-glare eye comfort.',
        imageUrl: 'unsplash:Monitor Light Bar',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.2, 0.5, 0.4, 0.4, 0.0, 0.8, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'tgad_cable',
        name: 'Cable Organizer',
        description: 'Clean desk setup.',
        imageUrl: 'unsplash:Cable Organizer',
        tags: ['Practical'],
        vector: [0.4, 0.0, 0.1, 0.2, 0.9, 0.4, 0.0, 0.7, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'tgad_vr',
        name: 'Oculus / Quest',
        description: 'VR immersion.',
        imageUrl: 'unsplash:Oculus / Quest',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.2, 0.6, 0.1, 0.0, 0.3, 1.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'tgad_watch',
        name: 'Smart Fitness Watch',
        description: 'Health metrics.',
        imageUrl: 'unsplash:Smart Fitness Watch',
        tags: ['Tech'],
        vector: [1.0, 0.4, 0.3, 0.6, 0.3, 0.1, 1.0, 0.7, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_sleep',
        name: 'Sleep Tracker Ring',
        description: 'Minimalist bio-metrics.',
        imageUrl: 'unsplash:Sleep Tracker Ring',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.5, 0.8, 0.1, 0.6, 0.8, 0.4, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'tgad_toothbrush',
        name: 'Electric Toothbrush',
        description: 'Sonic dental tech.',
        imageUrl: 'unsplash:Electric Toothbrush',
        tags: ['Tech'],
        vector: [0.9, 0.0, 0.0, 0.4, 0.7, 0.0, 0.6, 0.2, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'tgad_scale',
        name: 'Coffee Scale',
        description: 'Precision brewing.',
        imageUrl: 'unsplash:Coffee Scale',
        tags: ['Tech'],
        vector: [0.7, 0.0, 0.0, 0.3, 0.5, 0.5, 0.0, 0.6, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'tgad_frother',
        name: 'Milk Frother',
        description: 'Latte art at home.',
        imageUrl: 'unsplash:Milk Frother',
        tags: ['Gadget'],
        vector: [0.3, 0.0, 0.0, 0.2, 0.8, 0.7, 0.0, 0.4, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'tgad_kettle',
        name: 'Gooseneck Smart Kettle',
        description: 'Temp control pour.',
        imageUrl: 'unsplash:Gooseneck Smart Kettle',
        tags: ['Tech'],
        vector: [0.9, 0.0, 0.2, 0.7, 0.4, 0.6, 0.0, 0.5, 0.8, 1.0],
      ),
      SwipeItem(
        id: 'tgad_blender',
        name: 'High-Speed Blender',
        description: 'Smoothie power.',
        imageUrl: 'unsplash:High-Speed Blender',
        tags: ['Gadget'],
        vector: [0.6, 0.2, 0.0, 0.5, 0.7, 0.4, 0.8, 0.1, 0.1, 1.0],
      ),
      SwipeItem(
        id: 'tgad_airfryer',
        name: 'Digital Air Fryer',
        description: 'Crispy tech cooking.',
        imageUrl: 'unsplash:Digital Air Fryer',
        tags: ['Gadget'],
        vector: [0.8, 0.0, 0.0, 0.3, 0.9, 0.4, 0.3, 0.2, 0.1, 1.0],
      ),
      SwipeItem(
        id: 'tgad_toaster',
        name: 'Retro Toaster',
        description: 'Style meets breakfast.',
        imageUrl: 'unsplash:Retro Toaster',
        tags: ['Gadget'],
        vector: [0.2, 0.0, 0.4, 0.4, 0.6, 0.8, 0.0, 0.3, 0.9, 1.0],
      ),
      SwipeItem(
        id: 'tgad_frame',
        name: 'Digital Art Frame',
        description: 'Rotating gallery.',
        imageUrl: 'unsplash:Digital Art Frame',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.1, 0.6, 0.2, 0.6, 0.0, 0.8, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'tgad_soundbar',
        name: 'Compact Soundbar',
        description: 'TV audio upgrade.',
        imageUrl: 'unsplash:Compact Soundbar',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.2, 0.6, 0.4, 0.5, 0.0, 0.7, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'tgad_mouse_gaming',
        name: 'Lightweight Gaming Mouse',
        description: 'FPS speed.',
        imageUrl: 'unsplash:Lightweight Gaming Mouse',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.1, 0.4, 0.3, 0.0, 0.4, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'tgad_pad_xl',
        name: 'XL Desk Pad',
        description: 'Full desk coverage.',
        imageUrl: 'unsplash:XL Desk Pad',
        tags: ['Office'],
        vector: [0.4, 0.0, 0.3, 0.2, 0.7, 0.6, 0.0, 0.7, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'tgad_headset_stand',
        name: 'Desk Accessories',
        description: 'Organized, tidy, and functional.',
        imageUrl: 'unsplash:Desk Accessories',
        tags: ['Office'],
        vector: [0.2, 0.4, 0.6, 0.5, 0.4, 0.6, 0.0, 0.3, 0.9, 0.0],
      ),

      // --- GAMING & GEEK CULTURE (25 ITEMS) ---
      SwipeItem(
        id: 'brand_nintendo',
        name: 'Nintendo',
        description: 'Playful gaming brand.',
        imageUrl: 'unsplash:Nintendo',
        tags: ['Brand', 'Geek', 'Tech'],
        vector: [0.7, 0.0, 0.2, 0.3, 0.5, 0.6, 0.2, 1.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cat_handheld_consoles',
        name: 'Handheld Consoles',
        description: 'Portable gaming on the go.',
        imageUrl: 'unsplash:Handheld Game Console',
        tags: ['Category', 'Geek', 'Tech'],
        vector: [0.8, 0.0, 0.2, 0.3, 0.5, 0.5, 0.2, 1.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'brand_steam_deck',
        name: 'Steam Deck',
        description: 'Handheld PC platform.',
        imageUrl: 'unsplash:Steam Deck',
        tags: ['Brand', 'Geek', 'Tech'],
        vector: [1.0, 0.0, 0.1, 0.4, 0.3, 0.2, 0.0, 1.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'cat_handheld_pc_gaming',
        name: 'Handheld PC Gaming',
        description: 'PC games, portable form factor.',
        imageUrl: 'unsplash:Handheld PC Gaming',
        tags: ['Category', 'Geek', 'Tech'],
        vector: [1.0, 0.0, 0.1, 0.4, 0.3, 0.2, 0.0, 1.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'franchise_catan',
        name: 'Catan',
        description: 'Modern board game classic.',
        imageUrl: 'unsplash:Catan Board Game',
        tags: ['Category', 'Geek'],
        vector: [0.1, 0.1, 0.1, 0.1, 0.6, 0.8, 0.0, 1.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'cat_board_games',
        name: 'Board Games',
        description: 'Strategy, party games, and game nights.',
        imageUrl: 'unsplash:Board Game Night',
        tags: ['Category', 'Geek', 'Cozy'],
        vector: [0.0, 0.0, 0.1, 0.2, 0.7, 0.9, 0.0, 1.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'brand_playstation',
        name: 'PlayStation',
        description: 'Console gaming brand.',
        imageUrl: 'unsplash:PlayStation',
        tags: ['Brand', 'Geek', 'Tech'],
        vector: [0.9, 0.0, 0.2, 0.6, 0.2, 0.2, 0.0, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'cat_home_console_gaming',
        name: 'Home Console Gaming',
        description: 'Big screen, couch, and controllers.',
        imageUrl: 'unsplash:Console Gaming Living Room',
        tags: ['Category', 'Geek', 'Tech', 'Cozy'],
        vector: [0.9, 0.0, 0.1, 0.5, 0.3, 0.7, 0.0, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'brand_analogue_pocket',
        name: 'Analogue Pocket',
        description: 'Premium retro handheld.',
        imageUrl: 'unsplash:Analogue Pocket',
        tags: ['Brand', 'Geek', 'Tech', 'Luxury'],
        vector: [0.8, 0.0, 0.6, 0.8, 0.0, 0.3, 0.0, 1.0, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'cat_retro_gaming',
        name: 'Retro Gaming',
        description: 'Classic games and nostalgia.',
        imageUrl: 'unsplash:Retro Video Game',
        tags: ['Category', 'Geek'],
        vector: [0.6, 0.0, 0.4, 0.4, 0.4, 0.6, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'gam_topo',
        name: 'Topo Map Deskmat',
        description: 'Geographic desk art.',
        imageUrl: 'unsplash:Topo Map Deskmat',
        tags: ['Art'],
        vector: [0.2, 0.4, 0.4, 0.3, 0.6, 0.8, 0.0, 0.7, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'gam_gmk',
        name: 'Custom Keycaps',
        description: 'Double-shot ABS keys.',
        imageUrl: 'unsplash:Custom Keycaps',
        tags: ['Geek'],
        vector: [0.5, 0.0, 0.6, 0.7, 0.0, 0.2, 0.0, 1.0, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'gam_dnd',
        name: 'Tabletop RPGs',
        description: 'Story-driven roleplaying and campaigns.',
        imageUrl: 'unsplash:Tabletop RPG',
        tags: ['Gaming'],
        vector: [0.1, 0.0, 0.1, 0.0, 0.8, 0.7, 0.0, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'brand_magic_the_gathering',
        name: 'Magic: The Gathering',
        description: 'Fantasy strategy card game.',
        imageUrl: 'unsplash:Magic The Gathering',
        tags: ['Brand', 'Geek'],
        vector: [0.1, 0.0, 0.2, 0.2, 0.6, 0.5, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'franchise_pokemon',
        name: 'Pokémon',
        description: 'Collecting and nostalgia.',
        imageUrl: 'unsplash:Pokemon',
        tags: ['Category', 'Geek'],
        vector: [0.1, 0.0, 0.2, 0.3, 0.6, 0.5, 0.0, 1.0, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'cat_trading_card_games',
        name: 'Trading Card Games',
        description: 'Collecting, decks, and strategy.',
        imageUrl: 'unsplash:Trading Card Game',
        tags: ['Category', 'Geek'],
        vector: [0.1, 0.0, 0.2, 0.4, 0.6, 0.4, 0.0, 1.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'gam_gundam',
        name: 'Model Building',
        description: 'Building kits, detail, and patience.',
        imageUrl: 'unsplash:Model Building Kit',
        tags: ['Hobby'],
        vector: [0.3, 0.0, 0.1, 0.3, 0.5, 0.3, 0.0, 1.0, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'brand_lego',
        name: 'LEGO',
        description: 'Building brand.',
        imageUrl: 'unsplash:LEGO',
        tags: ['Brand', 'Geek', 'Art'],
        vector: [0.3, 0.0, 0.2, 0.4, 0.4, 0.8, 0.0, 1.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'franchise_star_wars',
        name: 'Star Wars',
        description: 'Sci-fi space saga.',
        imageUrl: 'unsplash:Star Wars',
        tags: ['Category', 'Geek'],
        vector: [0.5, 0.0, 0.1, 0.4, 0.4, 0.5, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'cat_building_sets',
        name: 'Building Sets',
        description: 'Collectible builds and displays.',
        imageUrl: 'unsplash:Building Blocks Set',
        tags: ['Category', 'Geek', 'Art'],
        vector: [0.3, 0.0, 0.2, 0.4, 0.4, 0.8, 0.0, 1.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'gam_manga',
        name: 'Manga & Comics',
        description: 'Serialized stories and art.',
        imageUrl: 'unsplash:Manga Comics',
        tags: ['Geek'],
        vector: [0.0, 0.0, 0.3, 0.4, 0.6, 0.7, 0.0, 0.9, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'gam_graphic_novel',
        name: 'Hardcover Graphic Novel',
        description: 'Visual storytelling.',
        imageUrl: 'unsplash:Hardcover Graphic Novel',
        tags: ['Art'],
        vector: [0.0, 0.0, 0.4, 0.5, 0.5, 0.8, 0.0, 0.8, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'franchise_elden_ring',
        name: 'Elden Ring',
        description: 'Dark fantasy game world.',
        imageUrl: 'unsplash:Elden Ring',
        tags: ['Category', 'Geek'],
        vector: [0.2, 0.0, 0.2, 0.5, 0.4, 0.6, 0.0, 1.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'cat_artbooks',
        name: 'Artbooks',
        description: 'Concept art and world-building.',
        imageUrl: 'unsplash:Art Book',
        tags: ['Category', 'Art', 'Geek'],
        vector: [0.2, 0.0, 0.2, 0.5, 0.4, 0.7, 0.0, 0.9, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'gam_controller',
        name: 'Pro Controller',
        description: 'Competitive input.',
        imageUrl: 'unsplash:Pro Controller',
        tags: ['Gaming'],
        vector: [0.9, 0.0, 0.1, 0.3, 0.4, 0.0, 0.3, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'gam_stick',
        name: 'Arcade Fight Stick',
        description: 'Fighting game precision.',
        imageUrl: 'unsplash:Arcade Fight Stick',
        tags: ['Gaming'],
        vector: [0.9, 0.0, 0.2, 0.4, 0.3, 0.0, 0.0, 1.0, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'gam_sim',
        name: 'Racing Wheel',
        description: 'Driving simulation.',
        imageUrl: 'unsplash:Racing Wheel',
        tags: ['Gaming'],
        vector: [1.0, 0.1, 0.1, 0.6, 0.2, 0.0, 0.5, 1.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'gam_vr_sensor',
        name: 'VR Base Station',
        description: 'Room-scale tracking.',
        imageUrl: 'unsplash:VR Base Station',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.4, 0.3, 0.0, 0.0, 1.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'gam_chair',
        name: 'Ergonomic Gaming Chair',
        description: 'Support for long sessions.',
        imageUrl: 'unsplash:Ergonomic Gaming Chair',
        tags: ['Office'],
        vector: [0.7, 0.0, 0.5, 0.6, 0.3, 0.6, 0.1, 0.9, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'gam_skin',
        name: 'Custom Console Skin',
        description: 'Vinyl console wrap.',
        imageUrl: 'unsplash:Custom Console Skin',
        tags: ['Art'],
        vector: [0.2, 0.0, 0.8, 0.2, 0.7, 0.4, 0.0, 0.8, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'gam_rpi',
        name: 'DIY Computing',
        description: 'Tinkering, projects, and circuits.',
        imageUrl: 'unsplash:DIY Electronics Computing',
        tags: ['Tech'],
        vector: [1.0, 0.0, 0.0, 0.1, 0.8, 0.1, 0.0, 1.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'gam_keychain',
        name: 'Pixel Art Keychain',
        description: 'Retro character accessory.',
        imageUrl: 'unsplash:Pixel Art Keychain',
        tags: ['Geek'],
        vector: [0.1, 0.0, 0.4, 0.0, 0.9, 0.4, 0.0, 0.7, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'gam_lights',
        name: 'Room Lighting',
        description: 'Ambience, LEDs, and mood lighting.',
        imageUrl: 'unsplash:Room LED Lighting',
        tags: ['Cozy', 'Tech'],
        vector: [0.9, 0.0, 0.3, 0.6, 0.2, 0.2, 0.0, 1.0, 0.9, 0.0],
      ),

      // --- FOOD & SNACK BRANDS (30 ITEMS) ---
      SwipeItem(
        id: 'fd_tonys',
        name: 'Tony\'s Chocolonely',
        description: 'Ethical chocolate.',
        imageUrl: 'unsplash:Chocolate Bar Candy Sweet',
        tags: ['Food'],
        vector: [0.0, 0.0, 0.4, 0.2, 0.6, 0.8, 0.0, 0.2, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'fd_momofuku',
        name: 'Chili Crunch',
        description: 'Spicy pantry gold.',
        imageUrl: 'unsplash:Chili Crunch',
        tags: ['Food'],
        vector: [0.0, 0.0, 0.3, 0.4, 0.3, 0.5, 0.0, 0.1, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'fd_bluebottle',
        name: 'Blue Bottle',
        description: 'Coffee brand.',
        imageUrl: 'unsplash:Blue Bottle Coffee',
        tags: ['Brand', 'Food'],
        vector: [0.0, 0.2, 0.5, 0.5, 0.2, 0.7, 0.0, 0.4, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'cat_coffee',
        name: 'Coffee',
        description: 'Specialty coffee and cafe culture.',
        imageUrl: 'unsplash:Coffee Beans Brew',
        tags: ['Category', 'Food'],
        vector: [0.1, 0.1, 0.2, 0.5, 0.5, 0.7, 0.1, 0.0, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'fd_liquid',
        name: 'Liquid Death',
        description: 'Canned water.',
        imageUrl: 'unsplash:Liquid Death',
        tags: ['Drink'],
        vector: [0.2, 0.5, 0.6, 0.1, 0.7, 0.1, 0.8, 0.6, 0.8, 1.0],
      ),
      SwipeItem(
        id: 'fd_truff',
        name: 'Truff',
        description: 'Sauce brand.',
        imageUrl: 'unsplash:Truff',
        tags: ['Brand', 'Food', 'Luxury'],
        vector: [0.0, 0.0, 0.5, 0.9, 0.0, 0.4, 0.0, 0.1, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'cat_hot_sauce',
        name: 'Hot Sauce',
        description: 'Heat, spice, and flavor.',
        imageUrl: 'unsplash:Hot Sauce Spicy',
        tags: ['Category', 'Food'],
        vector: [0.0, 0.0, 0.3, 0.4, 0.5, 0.4, 0.0, 0.1, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'fd_lacroix',
        name: 'LaCroix',
        description: 'Sparkling water.',
        imageUrl: 'unsplash:LaCroix',
        tags: ['Drink'],
        vector: [0.0, 0.0, 0.4, 0.0, 0.9, 0.4, 0.1, 0.2, 0.7, 1.0],
      ),
      SwipeItem(
        id: 'fd_ippodo',
        name: 'Ippodo',
        description: 'Tea brand.',
        imageUrl: 'unsplash:Ippodo Matcha',
        tags: ['Brand', 'Food'],
        vector: [0.0, 0.6, 0.4, 0.6, 0.3, 0.9, 0.3, 0.2, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'cat_matcha',
        name: 'Matcha',
        description: 'Green tea ritual and flavor.',
        imageUrl: 'unsplash:Matcha Tea',
        tags: ['Category', 'Food', 'Cozy'],
        vector: [0.0, 0.6, 0.3, 0.4, 0.4, 0.9, 0.2, 0.1, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'fd_ichiran',
        name: 'Instant Ramen',
        description: 'Tonkotsu gold.',
        imageUrl: 'unsplash:Instant Ramen',
        tags: ['Food'],
        vector: [0.0, 0.0, 0.2, 0.4, 0.5, 0.8, 0.0, 0.1, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'fd_flybyjing',
        name: 'Sichuan Crisp',
        description: 'Culture in a jar.',
        imageUrl: 'unsplash:Sichuan Crisp',
        tags: ['Food'],
        vector: [0.0, 0.1, 0.5, 0.4, 0.2, 0.4, 0.0, 0.3, 0.8, 1.0],
      ),
      SwipeItem(
        id: 'fd_oatly',
        name: 'Oatly Milk',
        description: 'Cult oat milk.',
        imageUrl: 'unsplash:Oatly Milk',
        tags: ['Drink'],
        vector: [0.1, 0.5, 0.6, 0.2, 0.6, 0.6, 0.2, 0.4, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'fd_ghirardelli',
        name: 'Dark Chocolate',
        description: 'San Fran classic.',
        imageUrl: 'unsplash:Dark Chocolate',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.2, 0.5, 0.6, 0.8, 0.0, 0.1, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'fd_lindt',
        name: 'Chocolate & Truffles',
        description: 'Rich, sweet, and indulgent.',
        imageUrl: 'unsplash:Chocolate Truffles',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.3, 0.6, 0.5, 0.8, 0.0, 0.1, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'fd_kinder',
        name: 'Kinder Bueno',
        description: 'Hazelnut cream.',
        imageUrl: 'unsplash:Kinder Bueno',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.2, 0.1, 0.8, 0.6, 0.0, 0.1, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'fd_haribo',
        name: 'Goldbears',
        description: 'Classic gummy.',
        imageUrl: 'unsplash:Goldbears',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.1, 0.0, 1.0, 0.4, 0.1, 0.2, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'fd_hichew',
        name: 'Hi-Chew',
        description: 'Japanese chewy candy.',
        imageUrl: 'unsplash:Hi-Chew',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.3, 0.2, 0.8, 0.4, 0.1, 0.4, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'fd_pocky',
        name: 'Strawberry Pocky',
        description: 'Biscuit sticks.',
        imageUrl: 'unsplash:Strawberry Pocky',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.4, 0.2, 0.8, 0.4, 0.1, 0.4, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'fd_takis',
        name: 'Takis Fuego',
        description: 'Intense chili lime.',
        imageUrl: 'unsplash:Takis Fuego',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.3, 0.0, 1.0, 0.2, 0.4, 0.4, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'fd_cheetos',
        name: 'Flaming Hot',
        description: 'Spicy snack cult.',
        imageUrl: 'unsplash:Flaming Hot',
        tags: ['Snack'],
        vector: [0.0, 0.0, 0.2, 0.0, 1.0, 0.2, 0.3, 0.3, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'fd_kettle',
        name: 'Sea Salt Vinegar',
        description: 'Extra crunchy chips.',
        imageUrl: 'unsplash:Sea Salt Vinegar',
        tags: ['Snack'],
        vector: [0.0, 0.1, 0.1, 0.1, 0.9, 0.4, 0.1, 0.1, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'fd_skinnypop',
        name: 'Popcorn',
        description: 'Light salty snack.',
        imageUrl: 'unsplash:Popcorn',
        tags: ['Snack'],
        vector: [0.0, 0.1, 0.1, 0.0, 0.9, 0.5, 0.6, 0.0, 0.1, 1.0],
      ),
      SwipeItem(
        id: 'fd_cliff',
        name: 'Protein Bar',
        description: 'Energy on the go.',
        imageUrl: 'unsplash:Protein Bar',
        tags: ['Active'],
        vector: [0.0, 0.6, 0.1, 0.1, 0.8, 0.1, 1.0, 0.0, 0.0, 1.0],
      ),
      SwipeItem(
        id: 'fd_rxbar',
        name: 'Whole Food Bar',
        description: 'Simple ingredients.',
        imageUrl: 'unsplash:Whole Food Bar',
        tags: ['Active'],
        vector: [0.0, 0.5, 0.1, 0.2, 0.8, 0.2, 0.9, 0.0, 0.0, 1.0],
      ),
      SwipeItem(
        id: 'fd_yerba',
        name: 'Guayaki Yerba',
        description: 'Clean caffeine.',
        imageUrl: 'unsplash:Guayaki Yerba',
        tags: ['Drink'],
        vector: [0.0, 0.7, 0.3, 0.2, 0.8, 0.4, 0.9, 0.0, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'fd_kombucha',
        name: 'Ginger Kombucha',
        description: 'Fermented healthy tea.',
        imageUrl: 'unsplash:Ginger Kombucha',
        tags: ['Drink'],
        vector: [0.0, 0.7, 0.2, 0.3, 0.6, 0.6, 0.8, 0.0, 0.1, 1.0],
      ),
      SwipeItem(
        id: 'fd_coldbrew',
        name: 'Canned Cold Brew',
        description: 'Nitrogen infused.',
        imageUrl: 'unsplash:Canned Cold Brew',
        tags: ['Drink'],
        vector: [0.2, 0.1, 0.4, 0.3, 0.7, 0.5, 0.4, 0.3, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'fd_hotcocoa',
        name: 'Gourmet Cocoa Mix',
        description: 'Rich winter drink.',
        imageUrl: 'unsplash:Gourmet Cocoa Mix',
        tags: ['Cozy'],
        vector: [0.0, 0.0, 0.1, 0.4, 0.6, 1.0, 0.0, 0.1, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'fd_tea',
        name: 'Tea',
        description: 'Herbal blends, ritual, and calm.',
        imageUrl: 'unsplash:Loose Leaf Tea',
        tags: ['Drink'],
        vector: [0.0, 0.5, 0.2, 0.6, 0.5, 0.9, 0.2, 0.2, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'fd_spices',
        name: 'Craft Spice Rack',
        description: 'Essential cooking set.',
        imageUrl: 'unsplash:Craft Spice Rack',
        tags: ['Cooking'],
        vector: [0.0, 0.2, 0.1, 0.4, 0.7, 0.6, 0.0, 0.3, 0.7, 1.0],
      ),
      SwipeItem(
        id: 'fd_oil',
        name: 'Cold Pressed Olive Oil',
        description: 'Premium finishing oil.',
        imageUrl: 'unsplash:Cold Pressed Olive Oil',
        tags: ['Cooking'],
        vector: [0.0, 0.3, 0.4, 0.7, 0.4, 0.6, 0.0, 0.1, 0.8, 1.0],
      ),
      SwipeItem(
        id: 'fd_honey',
        name: 'Hot Honey',
        description: 'Sweet and spicy drizzle.',
        imageUrl: 'unsplash:Hot Honey',
        tags: ['Food'],
        vector: [0.0, 0.2, 0.3, 0.3, 0.6, 0.6, 0.0, 0.2, 0.6, 1.0],
      ),

      // --- HOBBIES & EXPERIENCES (25 ITEMS) ---
      SwipeItem(
        id: 'hb_vinyl',
        name: 'Vinyl Collecting',
        description: 'Analog music.',
        imageUrl: 'unsplash:Vinyl Collecting',
        tags: ['Music'],
        vector: [0.3, 0.0, 0.6, 0.4, 0.2, 0.8, 0.0, 0.8, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'hb_pottery',
        name: 'Wheel Class',
        description: 'Hands-on clay.',
        imageUrl: 'unsplash:Wheel Class',
        tags: ['Art'],
        vector: [0.0, 0.5, 0.2, 0.3, 0.4, 0.9, 0.1, 0.1, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_hiking',
        name: 'Peak Bagging',
        description: 'Climbing mountains.',
        imageUrl: 'unsplash:Peak Bagging',
        tags: ['Active'],
        vector: [0.1, 1.0, 0.4, 0.2, 0.8, 0.1, 1.0, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_mixology',
        name: 'Cocktail Crafting',
        description: 'Home bar mastery.',
        imageUrl: 'unsplash:Cocktail Crafting',
        tags: ['Social'],
        vector: [0.1, 0.0, 0.4, 0.7, 0.3, 0.6, 0.0, 0.2, 0.6, 1.0],
      ),
      SwipeItem(
        id: 'hb_lego',
        name: 'Architecture',
        description: 'Buildings, design, and structure.',
        imageUrl: 'unsplash:Architecture Design',
        tags: ['Category', 'Art'],
        vector: [0.2, 0.0, 0.2, 0.5, 0.3, 0.7, 0.0, 0.4, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_film',
        name: '35mm Film Photo',
        description: 'Chemical image making.',
        imageUrl: 'unsplash:35mm Film Photo',
        tags: ['Art'],
        vector: [0.4, 0.4, 0.7, 0.4, 0.4, 0.3, 0.2, 0.6, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_bread',
        name: 'Sourdough Science',
        description: 'Art of the starter.',
        imageUrl: 'unsplash:Sourdough Science',
        tags: ['Food'],
        vector: [0.0, 0.3, 0.1, 0.2, 0.6, 1.0, 0.0, 0.2, 0.5, 1.0],
      ),
      SwipeItem(
        id: 'hb_dnd',
        name: 'Dungeons & Dragons',
        description: 'Fantasy roleplaying universe.',
        imageUrl: 'unsplash:Dungeons and Dragons',
        tags: ['Category', 'Geek'],
        vector: [0.1, 0.0, 0.1, 0.0, 0.8, 0.7, 0.0, 1.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'hb_plants',
        name: 'House Plant Care',
        description: 'Indoor jungle life.',
        imageUrl: 'unsplash:House Plant Care',
        tags: ['Nature'],
        vector: [0.0, 1.0, 0.2, 0.1, 0.6, 0.9, 0.2, 0.1, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'hb_cycling',
        name: 'Gravel Biking',
        description: 'Off-road distance.',
        imageUrl: 'unsplash:Gravel Biking',
        tags: ['Active'],
        vector: [0.5, 0.9, 0.3, 0.5, 0.2, 0.1, 1.0, 0.3, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'hb_running',
        name: '5K Training',
        description: 'Morning cardio.',
        imageUrl: 'unsplash:5K Training',
        tags: ['Active'],
        vector: [0.2, 0.5, 0.3, 0.2, 0.9, 0.0, 1.0, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_yoga',
        name: 'Hot Yoga',
        description: 'Flexibility and sweat.',
        imageUrl: 'unsplash:Hot Yoga',
        tags: ['Active'],
        vector: [0.0, 0.4, 0.3, 0.3, 0.6, 0.8, 1.0, 0.0, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'hb_meditation',
        name: 'Daily Mindfulness',
        description: 'Guided mental calm.',
        imageUrl: 'unsplash:Daily Mindfulness',
        tags: ['Wellness'],
        vector: [0.0, 0.6, 0.1, 0.2, 0.8, 1.0, 0.7, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'hb_painting',
        name: 'Oil Painting',
        description: 'Fine art expression.',
        imageUrl: 'unsplash:Oil Painting',
        tags: ['Art'],
        vector: [0.0, 0.3, 0.1, 0.4, 0.5, 0.7, 0.0, 0.3, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_knitting',
        name: 'Wool Knitting',
        description: 'Slow textile creation.',
        imageUrl: 'unsplash:Wool Knitting',
        tags: ['Hobby'],
        vector: [0.0, 0.2, 0.4, 0.2, 0.6, 1.0, 0.0, 0.2, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'hb_crochet',
        name: 'Amigurumi',
        description: 'Cute crochet figures.',
        imageUrl: 'unsplash:Amigurumi',
        tags: ['Hobby'],
        vector: [0.0, 0.1, 0.3, 0.1, 0.7, 1.0, 0.0, 0.5, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'hb_wood',
        name: 'Woodworking',
        description: 'Building with timber.',
        imageUrl: 'unsplash:Woodworking',
        tags: ['Hobby'],
        vector: [0.2, 0.6, 0.1, 0.4, 0.5, 0.4, 0.5, 0.3, 0.6, 0.0],
      ),
      SwipeItem(
        id: 'hb_camping',
        name: 'Wild Camping',
        description: 'Sleeping under stars.',
        imageUrl: 'unsplash:Wild Camping',
        tags: ['Outdoors'],
        vector: [0.1, 1.0, 0.2, 0.3, 0.9, 0.2, 0.9, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_birds',
        name: 'Bird Watching',
        description: 'Field identification.',
        imageUrl: 'unsplash:Bird Watching',
        tags: ['Nature'],
        vector: [0.0, 1.0, 0.1, 0.2, 0.8, 0.5, 0.3, 0.3, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'hb_chess',
        name: 'Speed Chess',
        description: 'Tactical board play.',
        imageUrl: 'unsplash:Speed Chess',
        tags: ['Hobby'],
        vector: [0.1, 0.0, 0.0, 0.1, 0.7, 0.4, 0.0, 1.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'hb_poker',
        name: 'Texas Holdem',
        description: 'Social card strategy.',
        imageUrl: 'unsplash:Texas Holdem',
        tags: ['Social'],
        vector: [0.1, 0.0, 0.3, 0.5, 0.6, 0.3, 0.0, 0.6, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'hb_tarot',
        name: 'Tarot Reading',
        description: 'Intuitive card work.',
        imageUrl: 'unsplash:Tarot Reading',
        tags: ['Wellness'],
        vector: [0.0, 0.2, 0.4, 0.3, 0.6, 0.8, 0.0, 0.6, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_journal',
        name: 'Bullet Journaling',
        description: 'Creative organization.',
        imageUrl: 'unsplash:Bullet Journaling',
        tags: ['Creative'],
        vector: [0.1, 0.1, 0.4, 0.2, 0.8, 0.9, 0.0, 0.7, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'hb_calligraphy',
        name: 'Ink Calligraphy',
        description: 'Formal script art.',
        imageUrl: 'unsplash:Ink Calligraphy',
        tags: ['Art'],
        vector: [0.0, 0.0, 0.3, 0.5, 0.6, 0.7, 0.0, 0.5, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'hb_puzzle',
        name: '1000 Piece Puzzle',
        description: 'Analog focus task.',
        imageUrl: 'unsplash:1000 Piece Puzzle',
        tags: ['Cozy'],
        vector: [0.0, 0.2, 0.1, 0.2, 0.8, 1.0, 0.0, 0.4, 0.7, 0.0],
      ),

      // --- HOME, SCENT & WELLNESS (25 ITEMS) ---
      SwipeItem(
        id: 'w_diptyque',
        name: 'Diptyque Candle',
        description: 'Parisian scent.',
        imageUrl: 'unsplash:Diptyque Candle',
        tags: ['Luxury'],
        vector: [0.0, 0.2, 0.6, 1.0, 0.0, 1.0, 0.0, 0.0, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'w_stanley',
        name: 'Stanley Tumbler',
        description: 'Insulated hydration.',
        imageUrl: 'unsplash:Stanley Tumbler',
        tags: ['Lifestyle'],
        vector: [0.0, 0.6, 0.4, 0.2, 0.5, 0.4, 0.8, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'w_aesop',
        name: 'Aesop Hand Wash',
        description: 'Botanical luxury.',
        imageUrl: 'unsplash:Aesop Hand Wash',
        tags: ['Wellness'],
        vector: [0.0, 0.5, 0.7, 0.9, 0.0, 0.8, 0.2, 0.2, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'w_lelabo',
        name: 'Santal 33',
        description: 'Iconic fragrance.',
        imageUrl: 'unsplash:Santal 33',
        tags: ['Luxury'],
        vector: [0.0, 0.4, 0.8, 1.0, 0.0, 0.5, 0.0, 0.2, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'w_yeti',
        name: 'Yeti Rambler',
        description: 'Tough travel mug.',
        imageUrl: 'unsplash:Yeti Rambler',
        tags: ['Rugged'],
        vector: [0.1, 0.9, 0.2, 0.5, 0.3, 0.4, 0.8, 0.1, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'w_hay',
        name: 'HAY Color Crates',
        description: 'Modern storage.',
        imageUrl: 'unsplash:HAY Color Crates',
        tags: ['Design'],
        vector: [0.0, 0.0, 0.6, 0.3, 0.7, 0.7, 0.0, 0.4, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'w_blanket',
        name: 'Weighted Blanket',
        description: 'Anxiety-reducing sleep.',
        imageUrl: 'unsplash:Weighted Blanket',
        tags: ['Wellness'],
        vector: [0.0, 0.0, 0.1, 0.3, 0.5, 1.0, 0.2, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'w_byredo',
        name: 'Byredo Perfume',
        description: 'Minimalist scent art.',
        imageUrl: 'unsplash:Byredo Perfume',
        tags: ['Luxury'],
        vector: [0.0, 0.1, 0.8, 1.0, 0.0, 0.6, 0.0, 0.3, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'w_malin',
        name: 'Malin+Goetz',
        description: 'Modern apothecary.',
        imageUrl: 'unsplash:Malin+Goetz',
        tags: ['Wellness'],
        vector: [0.0, 0.2, 0.7, 0.7, 0.3, 0.8, 0.2, 0.1, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'w_boysmells',
        name: 'Boy Smells Candle',
        description: 'Unexpected scents.',
        imageUrl: 'unsplash:Boy Smells Candle',
        tags: ['Home'],
        vector: [0.0, 0.2, 0.7, 0.6, 0.2, 0.9, 0.0, 0.4, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'w_pfcandle',
        name: 'PF Candle Co',
        description: 'Terra-cotta amber jars.',
        imageUrl: 'unsplash:PF Candle Co',
        tags: ['Home'],
        vector: [0.0, 0.7, 0.5, 0.3, 0.5, 0.9, 0.0, 0.3, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'w_silk',
        name: 'Silk Pillowcase',
        description: 'Skin and hair care.',
        imageUrl: 'unsplash:Silk Pillowcase',
        tags: ['Wellness'],
        vector: [0.0, 0.0, 0.6, 0.9, 0.2, 1.0, 0.0, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'w_mask',
        name: 'Contoured Sleep Mask',
        description: 'Total blackout rest.',
        imageUrl: 'unsplash:Contoured Sleep Mask',
        tags: ['Wellness'],
        vector: [0.0, 0.0, 0.2, 0.4, 0.6, 1.0, 0.1, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'w_diffuser',
        name: 'Stone Essential Diffuser',
        description: 'Scented atmosphere.',
        imageUrl: 'unsplash:Stone Essential Diffuser',
        tags: ['Home'],
        vector: [0.1, 0.5, 0.3, 0.6, 0.4, 0.9, 0.2, 0.4, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'w_bomb',
        name: 'Eucalyptus Bath Bomb',
        description: 'Spa at home.',
        imageUrl: 'unsplash:Eucalyptus Bath Bomb',
        tags: ['Wellness'],
        vector: [0.0, 0.6, 0.1, 0.3, 0.7, 1.0, 0.3, 0.1, 0.3, 0.0],
      ),
      SwipeItem(
        id: 'w_steamer',
        name: 'Aromatherapy Showers',
        description: 'Scent, steam, and relaxation.',
        imageUrl: 'unsplash:Aromatherapy Shower',
        tags: ['Wellness'],
        vector: [0.0, 0.4, 0.1, 0.3, 0.8, 0.9, 0.3, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'w_facemask',
        name: 'Clay Face Mask',
        description: 'Deep pore cleansing.',
        imageUrl: 'unsplash:Clay Face Mask',
        tags: ['Wellness'],
        vector: [0.0, 0.3, 0.2, 0.4, 0.7, 0.8, 0.4, 0.1, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'w_serum',
        name: 'Vitamin C Serum',
        description: 'Brightening skincare.',
        imageUrl: 'unsplash:Vitamin C Serum',
        tags: ['Wellness'],
        vector: [0.1, 0.2, 0.4, 0.8, 0.4, 0.6, 0.2, 0.1, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'w_guasha',
        name: 'Rose Quartz Gua Sha',
        description: 'Facial massage tool.',
        imageUrl: 'unsplash:Rose Quartz Gua Sha',
        tags: ['Wellness'],
        vector: [0.0, 0.3, 0.3, 0.6, 0.5, 0.9, 0.2, 0.2, 0.8, 0.0],
      ),
      SwipeItem(
        id: 'w_yoga_mat',
        name: 'Natural Rubber Mat',
        description: 'High-grip studio mat.',
        imageUrl: 'unsplash:Natural Rubber Mat',
        tags: ['Active'],
        vector: [0.1, 0.5, 0.3, 0.5, 0.5, 0.4, 1.0, 0.1, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'w_roller',
        name: 'Foam Roller',
        description: 'Muscle knot release.',
        imageUrl: 'unsplash:Foam Roller',
        tags: ['Active'],
        vector: [0.0, 0.2, 0.1, 0.2, 0.8, 0.3, 1.0, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'w_kettlebell',
        name: 'Cast Iron Kettlebell',
        description: 'Home strength training.',
        imageUrl: 'unsplash:Cast Iron Kettlebell',
        tags: ['Active'],
        vector: [0.0, 0.2, 0.1, 0.2, 0.8, 0.3, 1.0, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'w_bands',
        name: 'Resistance Bands',
        description: 'Portable gym gear.',
        imageUrl: 'unsplash:Resistance Bands',
        tags: ['Active'],
        vector: [0.0, 0.3, 0.1, 0.1, 0.9, 0.1, 1.0, 0.0, 0.0, 0.0],
      ),

      // --- EXPERIENCES, SUBSCRIPTIONS & PERSONALIZED (25 ITEMS) ---
      SwipeItem(
        id: 'exp_coffee_subscription',
        name: 'Coffee & Espresso',
        description: 'Coffee culture, beans, and brewing.',
        imageUrl: 'unsplash:Coffee and Espresso',
        tags: ['Category', 'Food'],
        vector: [0.1, 0.1, 0.2, 0.5, 0.5, 0.7, 0.1, 0.0, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'exp_tea_tasting',
        name: 'Tea & Cozy Drinks',
        description: 'Warm, calm, and comforting.',
        imageUrl: 'unsplash:Tea and Cozy Drinks',
        tags: ['Category', 'Cozy', 'Food'],
        vector: [0.0, 0.2, 0.2, 0.4, 0.6, 0.9, 0.0, 0.0, 0.2, 1.0],
      ),
      SwipeItem(
        id: 'exp_cooking_class',
        name: 'Cooking & Kitchen',
        description: 'Recipes, flavors, and kitchen fun.',
        imageUrl: 'unsplash:Cooking and Kitchen',
        tags: ['Category', 'Food'],
        vector: [0.1, 0.0, 0.2, 0.5, 0.4, 0.7, 0.2, 0.1, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'exp_wine_tasting',
        name: 'Wine & Tastings',
        description: 'Grown-up flavors and pairings.',
        imageUrl: 'unsplash:Wine and Tasting',
        tags: ['Category', 'Luxury', 'Food'],
        vector: [0.0, 0.2, 0.4, 0.9, 0.1, 0.6, 0.0, 0.0, 0.3, 1.0],
      ),
      SwipeItem(
        id: 'exp_concert_tickets',
        name: 'Live Music & Nights Out',
        description: 'Energy, crowds, and shared moments.',
        imageUrl: 'unsplash:Live Music Night Out',
        tags: ['Category', 'Geek'],
        vector: [0.1, 0.0, 0.5, 0.4, 0.5, 0.3, 0.5, 0.6, 0.4, 0.1],
      ),
      SwipeItem(
        id: 'exp_museum_membership',
        name: 'Museums & Exhibits',
        description: 'Art, exhibits, and culture.',
        imageUrl: 'unsplash:Museum Exhibit',
        tags: ['Category', 'Art'],
        vector: [0.0, 0.0, 0.2, 0.7, 0.2, 0.5, 0.0, 0.1, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'exp_book_subscription',
        name: 'Books & Reading',
        description: 'Stories, learning, and quiet time.',
        imageUrl: 'unsplash:Books Reading',
        tags: ['Category', 'Cozy'],
        vector: [0.0, 0.1, 0.4, 0.5, 0.5, 0.9, 0.0, 0.3, 0.7, 0.0],
      ),
      SwipeItem(
        id: 'exp_audio_subscription',
        name: 'Podcasts & Audiobooks',
        description: 'Audio-first entertainment.',
        imageUrl: 'unsplash:Podcast Listening',
        tags: ['Category', 'Tech', 'Geek'],
        vector: [0.7, 0.0, 0.3, 0.5, 0.6, 0.3, 0.2, 0.3, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'exp_streaming_bundle',
        name: 'Movies & Streaming',
        description: 'Shows, movies, and binge nights.',
        imageUrl: 'unsplash:Movie Night Streaming',
        tags: ['Category', 'Geek', 'Cozy'],
        vector: [0.6, 0.0, 0.1, 0.2, 0.8, 0.7, 0.0, 0.9, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'exp_gym_pass',
        name: 'Fitness & Training',
        description: 'Movement, progress, and routines.',
        imageUrl: 'unsplash:Fitness Training',
        tags: ['Category', 'Active'],
        vector: [0.0, 0.0, 0.1, 0.3, 0.7, 0.2, 1.0, 0.0, 0.0, 0.0],
      ),
      SwipeItem(
        id: 'exp_massage',
        name: 'Spa & Relaxation',
        description: 'Unwind, recovery, self-care.',
        imageUrl: 'unsplash:Spa Relaxation',
        tags: ['Category', 'Cozy', 'Active'],
        vector: [0.0, 0.2, 0.3, 0.6, 0.3, 1.0, 0.4, 0.0, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'exp_pottery_class',
        name: 'Crafts & Making Things',
        description: 'Hands-on projects and DIY.',
        imageUrl: 'unsplash:Arts and Crafts',
        tags: ['Category', 'Art'],
        vector: [0.0, 0.0, 0.3, 0.4, 0.6, 0.6, 0.1, 0.2, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'exp_photography_walk',
        name: 'Photography',
        description: 'Capturing moments and aesthetics.',
        imageUrl: 'unsplash:Photography Camera',
        tags: ['Category', 'Art', 'Tech'],
        vector: [0.6, 0.2, 0.2, 0.4, 0.6, 0.2, 0.2, 0.2, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'exp_camping_weekend',
        name: 'Camping & Outdoors',
        description: 'Trails, gear, and fresh air.',
        imageUrl: 'unsplash:Camping Outdoors',
        tags: ['Category', 'Outdoors', 'Active'],
        vector: [0.0, 1.0, 0.2, 0.3, 0.6, 0.5, 0.7, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'exp_national_park_pass',
        name: 'Nature & Parks',
        description: 'Scenery, hikes, and green space.',
        imageUrl: 'unsplash:Nature Park',
        tags: ['Category', 'Outdoors'],
        vector: [0.0, 1.0, 0.1, 0.2, 0.8, 0.4, 0.6, 0.0, 0.1, 0.0],
      ),
      SwipeItem(
        id: 'pers_monogram_wallet',
        name: 'Personalized Everyday Carry',
        description: 'Custom touches on daily essentials.',
        imageUrl: 'unsplash:Personalized Accessories',
        tags: ['Category', 'Style'],
        vector: [0.0, 0.0, 0.8, 0.8, 0.3, 0.2, 0.0, 0.0, 0.2, 0.0],
      ),
      SwipeItem(
        id: 'pers_custom_necklace',
        name: 'Personalized Jewelry',
        description: 'Initials, names, and meaningful pieces.',
        imageUrl: 'unsplash:Personalized Jewelry',
        tags: ['Category', 'Luxury', 'Style'],
        vector: [0.0, 0.0, 0.7, 1.0, 0.1, 0.3, 0.0, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'pers_pet_portrait',
        name: 'Personalized Art',
        description: 'Custom illustration or design.',
        imageUrl: 'unsplash:Custom Illustration',
        tags: ['Category', 'Art'],
        vector: [0.0, 0.2, 0.2, 0.6, 0.4, 0.6, 0.0, 0.2, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'pers_star_map',
        name: 'Meaningful Keepsakes',
        description: 'Sentimental, story-driven items.',
        imageUrl: 'unsplash:Meaningful Keepsake',
        tags: ['Category', 'Cozy', 'Art'],
        vector: [0.2, 0.0, 0.4, 0.7, 0.4, 0.8, 0.0, 0.3, 1.0, 0.0],
      ),
      SwipeItem(
        id: 'pers_photo_book',
        name: 'Photos & Memories',
        description: 'Moments, nostalgia, and highlights.',
        imageUrl: 'unsplash:Photo Memories',
        tags: ['Category', 'Cozy', 'Art'],
        vector: [0.2, 0.0, 0.4, 0.6, 0.6, 0.9, 0.0, 0.0, 0.9, 0.0],
      ),
      SwipeItem(
        id: 'pers_recipe_book',
        name: 'Food Traditions',
        description: 'Comfort foods and shared recipes.',
        imageUrl: 'unsplash:Family Cooking Recipes',
        tags: ['Category', 'Cozy', 'Food'],
        vector: [0.0, 0.0, 0.2, 0.5, 0.6, 1.0, 0.0, 0.0, 0.4, 1.0],
      ),
      SwipeItem(
        id: 'sub_snack_box',
        name: 'Snacks & Treats',
        description: 'Sweet, salty, and fun flavors.',
        imageUrl: 'unsplash:Snacks and Treats',
        tags: ['Category', 'Food'],
        vector: [0.0, 0.0, 0.2, 0.4, 0.6, 0.6, 0.0, 0.0, 0.1, 1.0],
      ),
      SwipeItem(
        id: 'sub_self_care_box',
        name: 'Self-Care & Wellness',
        description: 'Reset, recharge, and feel-good routines.',
        imageUrl: 'unsplash:Self Care Wellness',
        tags: ['Category', 'Cozy', 'Active'],
        vector: [0.0, 0.2, 0.3, 0.6, 0.4, 1.0, 0.4, 0.0, 0.5, 0.0],
      ),
      SwipeItem(
        id: 'sub_socks',
        name: 'Fun Basics',
        description: 'Everyday essentials with personality.',
        imageUrl: 'unsplash:Colorful Socks',
        tags: ['Category', 'Style', 'Budget'],
        vector: [0.0, 0.0, 0.9, 0.3, 0.8, 0.6, 0.0, 0.2, 0.4, 0.0],
      ),
      SwipeItem(
        id: 'exp_escape_room',
        name: 'Puzzle Experiences',
        description: 'Mysteries, riddles, and problem-solving.',
        imageUrl: 'unsplash:Puzzle Game',
        tags: ['Category', 'Geek'],
        vector: [0.2, 0.0, 0.2, 0.4, 0.6, 0.4, 0.3, 1.0, 0.2, 0.0],
      ),
    ];

    // Enrich tags + normalize vectors for consistency across the whole dataset.
    return items.map(_enrichItem).toList();
  }


  static SwipeItem _enrichItem(SwipeItem item) {
    final vector = _normalizeVector(item.vector);
    final tags = _normalizeTags(item.tags);

    // Add up to 2 canonical dimension tags based on the vector signal.
    final topIdx = _topKIndices(vector, 2);
    for (final idx in topIdx) {
      // Only add if it has meaningful weight.
      if (vector[idx] >= 0.65) {
        tags.add(_dimensionTags[idx]);
      }
    }

    return SwipeItem(
      id: item.id,
      name: item.name,
      description: item.description,
      imageUrl: item.imageUrl,
      tags: tags.toList(growable: false),
      vector: vector,
    );
  }

  static List<double> _normalizeVector(List<double> v) {
    final out = List<double>.filled(10, 0.0);
    for (int i = 0; i < 10 && i < v.length; i++) {
      final x = v[i];
      if (x.isNaN || x.isInfinite) {
        out[i] = 0.0;
      } else {
        out[i] = x.clamp(0.0, 1.0);
      }
    }
    return out;
  }

  static Set<String> _normalizeTags(List<String> tags) {
    const alias = {
      // Keep tags category-level and consistent.
      'Drink': 'Food',
      'Snack': 'Food',
      'Clothing': 'Style',
      'Wellness': 'Active',
      'Hobby': 'Art',
      'Experience': 'Category',
      'Subscription': 'Category',
      'Personalized': 'Category',
      'Practical': 'Budget',
    };
    final out = <String>{};
    for (final t in tags) {
      final trimmed = t.trim();
      if (trimmed.isEmpty) continue;
      out.add(alias[trimmed] ?? trimmed);
    }
    return out;
  }

  static List<int> _topKIndices(List<double> v, int k) {
    final idx = List<int>.generate(v.length, (i) => i);
    idx.sort((a, b) => v[b].compareTo(v[a]));
    return idx.take(k).toList();
  }
}